# """
# analyst.py

# Execute the plan generated by the plannerAgent.
# """

# from __future__ import annotations

# from src.services.analysis_service import AnalysisService
# from src.tools.chart_tool import ChartTool


# class AnalystAgent:

#     """
#     Execute Analytical Task.
#     """

#     def __init__(self):

#         self.analysis_service = AnalysisService()

#         self.chart_tool = ChartTool()

#     def execute(
#             self,
#             plan:dict,
#             df
#     ):
#         """
#             Execute Planned action.
#         """
#         action=plan.get(
#             "action"
#         )

#         if action=="summary":
#             return self.analysis_service.summary(
#                 df
#             )

#         elif action=="analysis":
#             return {
#                 "summary":
#                     self.analysis_service.summary(df),

#                 "description":
#                     self.analysis_service.describe(df)    
#             }

#         elif action == "chart":

#             return self.chart_tool.create_chart(
#                 df=df,
#                 chart_type=plan.get(
#                     "chart_type",
#                     "bar"
#                 ),
#                 x=plan.get("x"),
#                 y=plan.get("y")
#             )


#         else:

#             return {
#                 "message":
#                 "Action not supported yet"
#             }
        


"""
analyst.py

Execute the plan generated by the PlannerAgent.
"""

from __future__ import annotations

import pandas as pd

from src.services.analysis_service import AnalysisService
from src.tools.chart_tool import ChartTool
from src.tools.sql_tool import SQLTool
from src.tools.insight_tool import InsightTool
from src.tools.anomaly_tool import AnomalyTool


class AnalystAgent:
    """
    Execute analytical tasks.
    """

    def __init__(self):

        self.analysis_service = AnalysisService()

        self.chart_tool = ChartTool()

        self.sql_tool = SQLTool()

        self.insight_tool = InsightTool()

        self.anomaly_tool = AnomalyTool()

    def execute(
        self,
        plan: dict,
        df: pd.DataFrame,
    ):
        """
        Execute the action chosen by the planner.
        """

        action = plan.get("action", "analysis")

        # --------------------------------------------------
        # Summary
        # --------------------------------------------------

        if action == "summary":

            return self.analysis_service.summary(df)

        # --------------------------------------------------
        # Analysis
        # --------------------------------------------------

        elif action == "analysis":

            return {

                "summary":
                    self.analysis_service.summary(df),

                "description":
                    self.analysis_service.describe(df),

                "column_statistics":
                    self.analysis_service.column_statistics(df),

                "missing_values":
                    self.analysis_service.missing_values(df),

                "duplicates":
                    self.analysis_service.duplicates(df),

            }

        # --------------------------------------------------
        # Chart
        # --------------------------------------------------

        elif action == "chart":

            return self.chart_tool.create_chart(

                df=df,

                chart_type=plan.get(
                    "chart_type",
                    "bar"
                ),

                x=plan.get("x"),

                y=plan.get("y"),

            )

        # --------------------------------------------------
        # SQL
        # --------------------------------------------------

        elif action == "sql":

            sql_query = plan.get("sql")

            if not sql_query:

                return {
                    "error": "SQL query not found in execution plan."
                }

            return self.sql_tool.execute(
                df=df,
                query=sql_query,
            )

        # --------------------------------------------------
        # Business Insights
        # --------------------------------------------------

        elif action == "insight":

            return self.insight_tool.generate_insights(
                df
            )

        # --------------------------------------------------
        # Anomaly Detection
        # --------------------------------------------------

        elif action == "anomaly":

            return self.anomaly_tool.detect(
                df
            )

        # --------------------------------------------------
        # Unsupported
        # --------------------------------------------------

        return {
            "error": f"Unsupported action: {action}"
        }