"""
analyst.py

Execute the plan generated by the plannerAgent.
"""

from __future__ import annotations

from src.services.analysis_service import AnalysisService
from src.tools.chart_tool import ChartTool


class AnalystAgent:

    """
    Execute Analytical Task.
    """

    def __init__(self):

        self.analysis_service = AnalysisService()

        self.chart_tool = ChartTool()

    def execute(
            self,
            plan:dict,
            df
    ):
        """
            Execute Planned action.
        """
        action=plan.get(
            "action"
        )

        if action=="summary":
            return self.analysis_service.summary(
                df
            )

        elif action=="analysis":
            return {
                "summary":
                    self.analysis_service.summary(df),

                "description":
                    self.analysis_service.describe(df)    
            }

        elif action == "chart":

            return self.chart_tool.create_chart(
                df=df,
                chart_type=plan.get(
                    "chart_type",
                    "bar"
                ),
                x=plan.get("x"),
                y=plan.get("y")
            )


        else:

            return {
                "message":
                "Action not supported yet"
            }
        
